AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple web api template from SAM.
Resources:
  ApiGwAllowLogRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      RoleName: candd-AmazonAPIGatewayPushToCloudWatchLogs
  AttachApiGwCloudWatchRole:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::Sub: ${ApiGwAllowLogRole.Arn}
  SimpleGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: SimpleGateway
      MethodSettings:
      - DataTraceEnabled: true
        MetricsEnabled: false
        HttpMethod: '*'
        LoggingLevel: INFO
        ResourcePath: /*
    DependsOn: AttachApiGwCloudWatchRole
  SimpleApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld.lambda_handler
      Runtime: python3.8
      FunctionName: backendapi-created-sam
      Policies: AWSLambdaExecute
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /resource/helloworld
            Method: get
            RestApiId:
              Ref: SimpleGateway
      CodeUri: s3://candd/9d639ab53dc4e5e1bc847b7323b7e3b9
