AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB Crete
Parameters:
  TableName:
    Type: String
    Description: DynamoDB Table Name
    Default: sampletable
Resources:
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        -
          AttributeName: CreatedId
          AttributeType: S
        -
          AttributeName: timestamp
          AttributeType: N
        -
          AttributeName: name
          AttributeType: S
        -
          AttributeName: age
          AttributeType: N
      KeySchema:
        -
          AttributeName: CreatedId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      # TTL definition
      TimeToLiveSpecification:
        AttributeName: expiration_time
        Enabled: true
      LocalSecondaryIndexes: 
        - 
          IndexName: lsi-sample
          KeySchema: 
            - 
              AttributeName: CreatedId
              KeyType: HASH
            - 
              AttributeName: name
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - param1
              - param2
              - param3
      GlobalSecondaryIndexes:
        -
          IndexName: gsi-sample
          KeySchema: 
            - 
              AttributeName: name
              KeyType: HASH
            - 
              AttributeName: age
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

Outputs:
  DynamoDBTableName:
    Value:
      !Ref DDBTable
    Description: DynamoDB Table Name
