AWSTemplateFormatVersion: 2010-09-09
Description: "Root template"

Parameters:
  # Input Value
  VPCID:
    Type: String
    ConstraintDescription: "vpcid"
    Default: vpc-0886abb677f15301a
  ServiceName:
    Type: String
    ConstraintDescription: "service name"
    Default: jupyter
  DefaultSecGroup:
    Type: String
    ConstraintDescription: "default security group id"
    Default: sg-09b4d65064120bc8b
  EcsServiceRoleArn:
    Type: String
    ConstraintDescription: "ecs service role"
    Default : arn:aws:iam::504534391617:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS
  FileSystemId:
    Type: String
    ConstraintDescription: "attach efs id"
    Default : fs-062d92f9c14942b33
  FileSystemAccessPoint:
    Type: String
    ConstraintDescription: "attach efs access point id"
    Default : fsap-068f66155d9af3cf5

Resources:
  # Environment(Systems Parameter)
  VpcIdParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/jupyter/VpcId"
      Type: "String"
      Value: !Ref VPCID
  ServiceNameParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/jupyter/ServiceName"
      Type: "String"
      Value: !Ref ServiceName
      Description: "set prefix name at service group."
  DefaultSecGroupParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/jupyter/DefaultSecGroup"
      Type: "String"
      Value: !Ref DefaultSecGroup
      Description: "default security group id."
  EcsServiceRoleParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/jupyter/EcsServiceRole"
      Type: "String"
      Value: !Ref EcsServiceRoleArn
      Description: "ecs service role."
  FileSystemIdParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/jupyter/FileSystemId"
      Type: "String"
      Value: !Ref FileSystemId
      Description: "filesystem id."
  FileSystemApParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/jupyter/FileSystemAp"
      Type: "String"
      Value: !Ref FileSystemAccessPoint
      Description: "filesystem access point."

  # Create cloudFormation stack
  SubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./jupyter_subnet.yml
    DependsOn: ServiceNameParameter
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./jupyter_iam.yml
    DependsOn: ServiceNameParameter
  SecGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./jupyter_secgroup.yml
    DependsOn: IamStack
  EcsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./jupyter_ecs.yml
      Parameters:
        ExeIamRoleArn: !GetAtt IamStack.Outputs.EcsExeRoleArn
        JupyterSecGroup: !GetAtt SecGroupStack.Outputs.JupyterSecGroup
        JupyterSubnet: !GetAtt SubnetStack.Outputs.JupyterSubnet
    DependsOn: SecGroupStack
Outputs:
 IamName:
    Description: iam name
    Value: !GetAtt IamStack.Outputs.IamName
    Export:
      Name: iam-name
 SubnetName:
    Description: subnet name
    Value: !GetAtt SubnetStack.Outputs.JupyterSubnet
    Export:
      Name: subnet-name
