AWSTemplateFormatVersion: 2010-09-09
Description: Root template
Parameters:
  EcsRoleName:
    Type: String
    ConstraintDescription: role name
    Default: ecs-execute
  ServiceName:
    Type: String
    ConstraintDescription: service name
    Default: jupyter
  VPCID:
    Type: String
    ConstraintDescription: vpcid
    Default: vpc-0886abb677f15301a
  DefaultSecGroup:
    Type: String
    ConstraintDescription: default security group id
    Default: sg-09b4d65064120bc8b
Resources:
  VpcIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /jupyter/VpcId
      Type: String
      Value:
        Ref: VPCID
  RoleNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /jupyter/EcsRoleName
      Type: String
      Value:
        Ref: EcsRoleName
  ServiceNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /jupyter/ServiceName
      Type: String
      Value:
        Ref: ServiceName
      Description: set prefix name at service group.
  DefaultSecGroupParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /jupyter/SecGroupId
      Type: String
      Value:
        Ref: DefaultSecGroup
      Description: default security group id.
  SubnetStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/some-cfn-package/jupyter/28b924f5d55bd89d74beb9ac8527fa91.template
    DependsOn: ServiceNameParameter
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/some-cfn-package/jupyter/294c063a2cf0468a429dd1ac96e4b5dd.template
    DependsOn: ServiceNameParameter
  SecGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/some-cfn-package/jupyter/23e5040b1be8644e5f279bfe34f6838b.template
    DependsOn: ServiceNameParameter
  EcsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/some-cfn-package/jupyter/3b805bc6f037359bd7a1264015d030e1.template
      Parameters:
        ExeIamRoleArn:
          Fn::GetAtt:
          - IamStack
          - Outputs.EcsExeRoleArn
    DependsOn: IamStack
Outputs:
  IamName:
    Description: iam name
    Value:
      Fn::GetAtt:
      - IamStack
      - Outputs.IamName
    Export:
      Name: iam-name
  SubnetName:
    Description: subnet name
    Value:
      Fn::GetAtt:
      - SubnetStack
      - Outputs.SubnetName
    Export:
      Name: subnet-name
